{% set name = "django-avatar" %}
{% set version = "7.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-avatar-{{ version }}.tar.gz
  sha256: cc0561a61395ec68af2a15d3008431a8b695a266e4f33339f139e2f40a5fc7bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.6,<=3.8
  run:
    - django >=1.11,<3.0
    - django-appconf
    - pillow
    - python >3.6,<=3.8

test:
  imports:
    - avatar
    - avatar.management

  commands:
    - pip check

  requires:
    - pip

about:
  home: http://github.com/grantmcconnaughey/django-avatar/
  summary: A Django app for handling user avatars
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mxr-conda
