{% set name = "django-avatar" %}
{% set version = "8.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2c4550489be08e9e5fe47b6c82afaba111a9c20d83957d5b660c63ea3b0eb5f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=65.6.3
    - wheel
    - pip
  run:
    - python >=3.8
    - django >=3.2
    - pillow >=10.0.1
    - django-appconf >=1.0.5
    - dnspython >=2.3.0

test:
  imports:
    - avatar
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Django app for handling user avatars
  home: https://github.com/jazzband/django-avatar
  license: BSD-3-Clause AND BSD-4-Clause
  license_file:
    - LICENSE.txt
    - avatar/templates/notification/avatar_updated/notice.html
    - avatar/templates/notification/avatar_friend_updated/notice.html

extra:
  recipe-maintainers:
    - rxm7706
    - mxr-conda
