{% set name = "django-avatar" %}
{% set version = "7.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-avatar-{{ version }}.tar.gz
  sha256: ee88d877d230249f01d4540fc0e22d7d10639458b8ba4863d901d61d9f74f8ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.6,<=3.8
  run:
    - django >=1.11,<3.0
    - django-appconf
    - pillow
    - python >3.6,<=3.8

test:
  imports:
    - avatar
    - avatar.management

  commands:
    - pip check

  requires:
    - pip

about:
  home: http://github.com/grantmcconnaughey/django-avatar/
  summary: A Django app for handling user avatars
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mxr-conda
